// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADHF1683j-aPJ6_A0fRAZcLQguxZWXOwU',
    appId: '1:762949465886:web:fa2b9aac5479cf7f95fb0f',
    messagingSenderId: '762949465886',
    projectId: 'delivery-boy-103c0',
    authDomain: 'delivery-boy-103c0.firebaseapp.com',
    storageBucket: 'delivery-boy-103c0.appspot.com',
    measurementId: 'G-132T0Y05P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVPVF_Mqg6v6otggDmwQOTHVAbLKifAA',
    appId: '1:762949465886:android:23a13f8c20a09d9a95fb0f',
    messagingSenderId: '762949465886',
    projectId: 'delivery-boy-103c0',
    storageBucket: 'delivery-boy-103c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJoUbWTSpTNy9D5idhaKE4tV_GsnMKdn8',
    appId: '1:762949465886:ios:99b1e0943e7b18fb95fb0f',
    messagingSenderId: '762949465886',
    projectId: 'delivery-boy-103c0',
    storageBucket: 'delivery-boy-103c0.appspot.com',
    iosBundleId: 'com.example.deliveryBoyApp',
  );
}
